services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb

  node-app:
    build:
      context: .
      dockerfile: node-app/Dockerfile
    restart: always
    ports:
      - "3002:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: mydb
